language: ruby
rvm:
- 2.2.5

git:
  submodules: false
branches:
  only:
  - refresh

sudo: false

script: ./scripts/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  provider: s3
  access_key_id: AKIAIXFWJ2ZPKD34XXTA
  secret_access_key:
    secure: bfdrNvmTQYsh/B/1ZYsvusFzzq7pSpBytGn5+l4tcY1pttmY/i6yHpY/lK5QWpN5rMUZ0B/ZyGNLoDSo1uucgC5MtYZA2YazX0ZLuTbSeLGN1wAtrvTwZLVxrLSzBSX+pdIBT3pHQAUdFg0TwRtWFsCC8DvRlkZzvokUoV5cChBJDyVmh2apnxxKaffFepGc4dP/TOipL3ItrPR41/qiygHTZQCOpKU7xazD/tj7RYNgSVOmDZ7hXXX2V7bU3K5Msh4RxM4/zhvjlm1EJCF4xzHl63zCEAxxlXrtd4bs1QhvyKYDTIckagcO6vCEh3JkSKflhtUgN3VrgHBoAvNAEDQ0JtrjuU4b2CV538lEOqvIgF/fNNoygqxcD+RyPeY7P5gZYUOg9zMS20TNffJOOo06CJffCAOxbqUFoMlQNnw0svvb4chmoZ5tTgzh4gZj8tdGGJvG7bgUWUK2uBwE/gALV2BPDRsS3CHGqd2Iy3J0Ml5YPQY+amt602uRwjsRcRe1OChPolRpIL7mf02D/jd0vzf+H6Aj4RQaIHy5YMXXsNUzNdstp22nL7ZusfQFG7PO4FjCs1aLkWnxve8o3C1tJTVoz7jPvomavYgy0EbgCxdE6LFxP1MZcb6fVoVDhZ9bLs2clzGKOP/Esm/IeqNAWd339zndwvPpB4wqdaU=
  bucket: shuttleworthfoundation-staging
  local-dir: _site
  acl: public_read
