language: ruby
rvm:
- 2.2.5

git:
  submodules: false
branches:
  only:
  - master

sudo: false

script: ./scripts/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  provider: s3
  access_key_id: AKIAICDQUQMCWON62TAQ
  secret_access_key:
    secure: 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
  region: us-east-1
  bucket: test.shuttleworthfoundation.org
  skip_cleanup: true
  local-dir: _site
  acl: public_read
  on:
    branch: master
