##
# SITE SETTINGS
##
title: The Shuttleworth Foundation
email: jason@shuttleworthfoundation.org
description: "We're the Shuttleworth Foundation. We provide funding for dynamic leaders who are at the forefront of social change."
baseurl: ""
url: "http://shuttleworthfoundation.org"
twitter_username: ShuttleworthFdn
github_username: jasonhudson


##
# BUILD SETTINGS
##
markdown: kramdown
permalink: pretty
breadcrumb_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
#gems:
#  - jekyll-redirect-from

exclude: [Makefile, README.md]


##
# COLLECTIONS
##
collections:
  fellows:
    output: true
  team:
    output: true

